name: Build_Alpha

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    
    - name: Setup up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Show dotnet Version
      run: dotnet --version
    - name: Show java Version
      run: java -version  
    - name: Setup Alpha Nacos Server
      run: |
        wget https://hub.fastgit.org/alibaba/nacos/releases/download/2.0.0-ALPHA.2/nacos-server-2.0.0-ALPHA.2.tar.gz
        tar -xvf nacos-server-2.0.0-ALPHA.2.tar.gz
        cd nacos/bin
        chmod 755 startup.sh
        nohup ./startup.sh -m standalone 2>&1 &
        sleep 30
        pwd
        curl "127.0.0.1:8848/nacos/v1/ns/operator/metrics"


